### ISSUE TITLE
Move to go mod replacing current dep

### ISSUE THREAD

**Issue by surajssd** [servicemeshinterface/smi-adapter-istio#25]
Right now the repo uses `dep` for dependency management, but replace it with go mod.

**Comment by surajssd** [comment]
Ran into issue while implementing this https://github.com/operator-framework/operator-sdk/issues/1436 and I think we should wait till then.

**Comment by rickducott** [comment]
Is there something we're waiting on related to the operator-sdk issue? That issue is closed and from the discussion there it seems operator projects with go mod shouldn't be blocked.
