### ISSUE TITLE
rename repo to smi-istio-operator?

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-adapter-istio#53]
Should we rename this repo to smi-istio-operator? The adapter language is very vague. This is technically an operator and I think the project would be much easier to understand with this name change. Thoughts?

cc/ @slack @lachie83 @grampelberg @bridgetkromhout

**Comment by bridgetkromhout** [comment]
Do we still want to rename this repo?

**Comment by bridgetkromhout** [comment]
We discussed this at the April 1, 2020 meeting and it was determined that nobody now thinks this repo needs to be renamed (including @michelleN).
