### ISSUE TITLE
move smi repos to another org?

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-adapter-istio#54]
We could move the SMI related repos to their own github org. I currently have github.com/service-mesh-interface and github.com/servicemeshinterface. It'd be nice to have everything in one logical place dedicated to SMI to help create a community around that. It's easier from a management perspective to keep it all in deislabs though.

Thoughts? Any other pros/cons people can think of?

**Comment by bridgetkromhout** [comment]
The repos have been moved to their own org (https://github.com/servicemeshinterface/) due to the CNCF donation.
