### ISSUE TITLE
add using smi-adapter-istio to smi-spec.io?

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-adapter-istio#59]
There is a website/landing page at smi-spec.io that talks about the spec but doesn't mention any implementations. Do we want to start adding links to the website around how to use SMI with Istio and other providers?

**Comment by bridgetkromhout** [comment]
When merged, https://github.com/servicemeshinterface/smi-spec.io/pull/7 will provide more visibility into available implementations.
